### ISSUE TITLE
update documentation that it requires python 3.

### ISSUE THREAD

**Issue by robert-figura** [pengutronix/flamingo#13]
Installing flamingo with pip2 or pip fails on import with this backtrace:

```
$ pip install flamingo
Collecting flamingo
  Using cached https://files.pythonhosted.org/packages/86/58/d53a3dc11916acd1b9ec17966b23bc4868da8a22aa6012600730c48a837d/flamingo-0.10.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/run/user/rfigura/pip-install-3RYxRR/flamingo/setup.py", line 7, in <module>
        import flamingo
      File "flamingo/__init__.py", line 3, in <module>
        from flamingo.core.plugins.hooks import hook  # NOQA
      File "flamingo/core/plugins/__init__.py", line 4, in <module>
        from .media import Media  # NOQA
      File "flamingo/core/plugins/media.py", line 3, in <module>
        from flamingo.core.data_model import ContentSet, Content
      File "flamingo/core/data_model.py", line 4, in <module>
        from textwrap import shorten
    ImportError: cannot import name shorten
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /
```

Under debian 10.0 you can install pip3 like this:

```
root# apt install python3-pip
```

**Comment by robert-figura** [comment]
I'm sorry, I seem to have overlooked that it already says "python-3 based". Nevermind %-)

**Comment by fscherf** [comment]
Hi @robert-figura,

No problem, thanks for testing an reporting anyway :)
